### ISSUE TITLE
TypeScript files are not being transpiled

### ISSUE THREAD

**Issue by agisboye** [EddyVerbruggen/nativescript-feedback#1]
I'm having trouble using this plugin in a vanilla JS project. It seems that the .ts files are not being transpiled. The plugin folder inside `tns_modules` contains only TypeScript files.

This is the only plugin I'm having trouble with. All other plugins with .ts sources are transpiled before being installed.

**Comment by EddyVerbruggen** [comment]
Are you installing this plugin from npm or github?

**Comment by agisboye** [comment]
I'm doing a `tns plugin add nativescript-feedback` which adds the plugin to package.json and installs with npm. I install all other plugins the same way, and none of them have any issues. 🤔

**Comment by EddyVerbruggen** [comment]
I'll take a look in about an hour. Thx.

**Comment by EddyVerbruggen** [comment]
Sorry for the inconvenience, 1.0.2 fixes the issue.

**Comment by agisboye** [comment]
That did the trick! Thanks for looking into the issue.
