### ISSUE TITLE
Enhancement: ability to show multiple message stacking them one over another 

### ISSUE THREAD

**Issue by terreb** [EddyVerbruggen/nativescript-feedback#10]
Hi and thank you for the awesome plugin!

Would be a cool enhancement if we can instantiate multiple feedbacks and show all of them on the screen, so that the second feedback would stack below the first one (if the position for both is top) if the first one haven't been clicked yet or timed out (with short duration param). This would cover cases where there is a need to show multiple messages one by one and we want to make sure the user read all of them before closing. We sure can show one then wait for the user to click it before showing another, but preferably they would appear in sync with related events, so shown right before the even started.

**Comment by EddyVerbruggen** [comment]
I understand the requirement, but simply put: the [Android](https://github.com/Tapadoo/Alerter) nor [iOS](https://github.com/ilyainyushin/ISMessages) library I've used supports that.

**Comment by terreb** [comment]
Ok, thank you for the tip. Is there currently a way to listen for the hide event or have a custom handler for onHide like for onTap?

**Comment by EddyVerbruggen** [comment]
No there is not, and it would depend on the duration of the animation as well (should it fire before or after?). But it can be simulated by using a timeout that relates to the duration the message is shown (and taking into account the user can dismiss the message himself). This may be a candidate for a new feature, but I'm not able to pour time into this atm.

**Comment by terreb** [comment]
Using timeout to know exactly when the feedback gets hidden and therefore implement a custom handler is a perfect idea, thanks a lot man, will be using this as workaround!

**Comment by larssn** [comment]
Interested in a PR for a `onShow()`/`onHide()` callback? Both native plugins seems to support it, so I'm thinking it wouldn't be too hard.

**Comment by EddyVerbruggen** [comment]
Absolutely!
