### ISSUE TITLE
Add support for iPhone X

### ISSUE THREAD

**Issue by hettiger** [EddyVerbruggen/nativescript-feedback#12]
![bildschirmfoto 2017-11-08 um 13 11 03](https://user-images.githubusercontent.com/4583871/32548667-c40a5a20-c486-11e7-8fb4-23617ae06c0e.png)
![bildschirmfoto 2017-11-08 um 13 12 03](https://user-images.githubusercontent.com/4583871/32548668-c420a1cc-c486-11e7-84e5-0be01cc048a7.png)

Currently unfortunately it looks terrible on the new iPhone so the plugin is not usable basically.

**Comment by EddyVerbruggen** [comment]
Thanks for opening this issue - I just noticed it too.

**Comment by EddyVerbruggen** [comment]
By the way, this plugin wraps (and expands upon) [this iOS library](https://github.com/ilyainyushin/ISMessages) - there's no issue for iPhone X in that repo yet so I'm afraid I'll have to fix that myself and send that repo a PR.

**Comment by hettiger** [comment]
I was just about to open an issue there as well but since you're about to create a PR there I'll leave it up to you. Thank you @EddyVerbruggen  👍

**Comment by EddyVerbruggen** [comment]
Version 1.0.0 is now available 🎉

iPhone X (or more precisely: devices with a specific *safe area inset*) now renders like this (no changes for other devices):

![simulator screen shot - iphone x - 2017-11-08 at 15 11 19](https://user-images.githubusercontent.com/1426370/32553394-1c3db146-c497-11e7-9359-061dbb89c871.png)

![simulator screen shot - iphone x - 2017-11-08 at 15 11 22](https://user-images.githubusercontent.com/1426370/32553393-1c22f360-c497-11e7-8278-cbb5dbb3798f.png)

**Comment by hettiger** [comment]
That is really amazing @EddyVerbruggen Thank you!

**Comment by packytagliaferro** [comment]
I am using `"nativescript-feedback": "^1.3.1",` and still seeing this issue:

![screen shot 2018-12-05 at 4 29 59 pm](https://user-images.githubusercontent.com/1316850/49553181-52613b00-f8ab-11e8-8369-d36a6b85ebe4.png)
