### ISSUE TITLE
IOS build failed ISMessages.m

### ISSUE THREAD

**Issue by dembal1990** [EddyVerbruggen/nativescript-feedback#13]
Hy!

I created a new hello world project with:
`tns create HelloWorld --template nativescript-template-ng-tutorial`

and add this plugin:
`tns plugin add nativescript-feedback`

I catch the next error when I run on iOS emulator:

```
Building project...
Xcode build...
=== BUILD TARGET ISMessages OF PROJECT Pods WITH CONFIGURATION Debug ===
/Users/dembal/HelloWorld/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:145:9: error: unexpected '@'
      in program
    if (@available(iOS 11.0, *)) {
        ^
/Users/dembal/HelloWorld/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:148:38: error: property
      'safeAreaInsets' not found on object of type 'UIWindow *'
            insetCorrection = window.safeAreaInsets.bottom;
                                     ^
/Users/dembal/HelloWorld/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:191:9: error: unexpected '@'
      in program
    if (@available(iOS 11.0, *)) {
        ^
/Users/dembal/HelloWorld/platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:194:39: error: property
      'safeAreaInsets' not found on object of type 'UIWindow *'
            insetCorrection = -window.safeAreaInsets.bottom;
                                      ^
4 errors generated.
** BUILD FAILED **

Unable to apply changes on device: ********************** Error is: Command xcodebuild failed with exit code 65.
```

tons info:
│ Component        │ Current version │ Latest version │ Information      │
│ nativescript      │ 3.3.1           │ 3.3.1          │ Up to date       │
│ tns-core-modules │ 3.1.1           │ 3.3.0          │ Update available │
│ tns-android      │                 │ 3.3.1          │ Not installed    │
│ tns-ios          │ 3.3.0           │ 3.3.0          │ Up to date       │

**Comment by EddyVerbruggen** [comment]
Hi, can you please update your Xcode app and try again?

**Comment by pikho** [comment]
Hi, I also found this error while my Xcode is up-to-date.
Using nativescript-feedback 1.0.6 gets no problem.

**Comment by EddyVerbruggen** [comment]
With Xcode 9 installed this should really be fine.

**Comment by KevinBeckers** [comment]
I have also problems with ISMessages

`ld: warning: directory not found for option '-F/Users/Kevin/Library/Developer/Xcode/DerivedData/food-eqsyyseunqnkasfnularauyheheh/Build/Products/Debug-iphoneos/ISMessages'
ld: framework not found ISMessages`

**Comment by jcfrane** [comment]
I have this now on Xcode 11 :(
