### ISSUE TITLE
 TypeError: Cannot read property 'Alerter' of undefined

### ISSUE THREAD

**Issue by aloketewary** [EddyVerbruggen/nativescript-feedback#15]
Unable to use this plugin when using it with angular just used whatever you write to include in your readme file.

After Watching closely this line probably root cause of the error, in your feedback.android.js

 ```
var alerter = com.tapadoo.alerter.Alerter.create(application.android.foregroundActivity)
                .setTitle(options.title)
                .setText(options.message)
                .setDuration(options.duration ? options.duration : 4000);
```

**Comment by EddyVerbruggen** [comment]
This is an Angular app (deployed to the appstores) using this plugin: https://github.com/EddyVerbruggen/nativescript-pluginshowcase/tree/master/app/feedback

**Comment by aloketewary** [comment]
Thanks the fallback issue was due to plugin install and nativescript can't deploy this right a way, so basically I remove platform and node_modules folder from my project and then run tns run android,,, and voila it's running smooth thanks for the support by the way..

**Comment by filipbarak** [comment]
Hi, got the same error @aloketewary pointed out, followed his steps and the error was resolved.

Maybe you should address this in the readme @EddyVerbruggen. 

Thanks anyway, this fixed the issue.

**Comment by EddyVerbruggen** [comment]
@filipbarak The way @aloketewary fixed it is actually the same for all plugins using native library dependencies, so actually it may be better to add some logic to he NativeScript-CLI instead.

If you strongly feel this repo should have a note then please feel free to send a PR.
