### ISSUE TITLE
Adding margin to the feedback popup

### ISSUE THREAD

**Issue by bozhidarc** [EddyVerbruggen/nativescript-feedback#16]
Is it possible to be added margin to the message popup?
The margin exists on the original lib for iOS. 

https://camo.githubusercontent.com/906046a70d1c4113ef6aaa51ca4504e6a0895c8a/687474703a2f2f7332302e706f7374696d672e6f72672f75736d6775673534742f696d6167652e706e67

**Comment by EddyVerbruggen** [comment]
It’s possible, but I removed it on purpose to align with the Android look.

**Comment by bozhidarc** [comment]
Can you added back as an optional attribute?

**Comment by EddyVerbruggen** [comment]
The problem is that the [Android library](https://github.com/Tapadoo/Alerter) must then be altered as well. So I'm not planning to.
