### ISSUE TITLE
error: unrecognized platform name iOS

### ISSUE THREAD

**Issue by mayoricodevault** [EddyVerbruggen/nativescript-feedback#18]
# tns debug ios --device 1

platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:146:20: error: unrecognized platform name iOS
    if (@available(iOS 11.0, *)) {
                   ^
platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:149:38: error: property 'safeAreaInsets' not found on object of type 'UIWindow *'
            insetCorrection = window.safeAreaInsets.bottom;
                                     ^
platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:201:20: error: unrecognized platform name iOS
    if (@available(iOS 11.0, *)) {
                   ^
platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:204:39: error: property 'safeAreaInsets' not found on object of type 'UIWindow *'
            insetCorrection = -window.safeAreaInsets.bottom;
                                      ^
platforms/ios/Pods/ISMessages/ISMessages/Classes/ISMessages.m:183:1: warning: conflicting return type in implementation of
      'accessibilityPerformEscape': 'BOOL' (aka 'signed char') vs 'bool' [-Wmismatched-return-types]
- (bool)accessibilityPerformEscape {
^  ~~~~
In module 'UIKit' imported from /Users/mikemayori/Desktop/aws/aws-transcribe/platforms/ios/Pods/Target Support Files/ISMessages/ISMessages-prefix.pch:2:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS10.3.sdk/System/Library/Frameworks/UIKit.framework/Headers/UIAccessibility.h:296:1: note:
      previous definition is here
- (BOOL)accessibilityPerformEscape NS_AVAILABLE_IOS(5_0);

**Comment by apopiidoru** [comment]
any update on this ?

**Comment by EddyVerbruggen** [comment]
Update Xcode and you're good.
