### ISSUE TITLE
build failing after updating to latest version of NS n NS core modules

### ISSUE THREAD

**Issue by mhmo91** [EddyVerbruggen/nativescript-feedback#19]
I'm getting this after upgrading to the latest version of NS.
![image](https://user-images.githubusercontent.com/3815200/38136065-418dbdd4-341c-11e8-96e3-ae7c53d94006.png)

my packages.json is

{
  "description": "Darts Solutions Inc. (DSI) has supported a number of Ontario Government and private sector IT initiatives. Experience in social services has led DSI to realize many opportunities to help people with developmental disabilities to achieve their goals, participate in their communities, and have choice about how they and their families receive supports. MyDirectPlan (MDP) is a result of years of studying and meeting Passport and Direct Funding Families.",
  "keywords": [
    "My direct plan",
    "funding management"
  ],
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "version": "0.1.0",
  "homepage": "https://github.com/NativeScript/nativescript-sdk-examples-ng",
  "repository": {
    "type": "git",
    "url": "https://github.com/NativeScript/nativescript-sdk-examples-ng"
  },
  "nativescript": {
    "id": "org.nativescript.MyDirectPlan",
    "tns-ios": {
      "version": "next"
    },
    "tns-android": {
      "version": "4.0.0-2018.3.22.2"
    }
  },
  "scripts": {
    "tslint": "tslint --project tsconfig.json --config tslint.json",
    "ns-bundle": "ns-bundle",
    "start-android-bundle": "npm run ns-bundle --android --run-app",
    "start-ios-bundle": "npm run ns-bundle --ios --run-app",
    "build-android-bundle": "npm run ns-bundle --android --build-app",
    "build-ios-bundle": "npm run ns-bundle --ios --build-app",
    "publish-ios-bundle": "npm run ns-bundle --ios --publish-app",
    "generate-android-snapshot": "generate-android-snapshot --targetArchs arm,arm64,ia32 --install"
  },
  "dependencies": {
    "@angular/animations": "^5.2.9",
    "@angular/common": "^5.2.9",
    "@angular/compiler": "^5.2.9",
    "@angular/core": "^5.2.9",
    "@angular/forms": "^5.2.9",
    "@angular/http": "^5.2.9",
    "@angular/platform-browser": "^5.2.9",
    "@angular/platform-browser-dynamic": "^5.2.9",
    "@angular/router": "^5.2.9",
    "moment": "^2.21.0",
    "nativescript-angular": "^5.3.0-2018-03-29-03",
    "nativescript-background-http": "^3.2.2",
    "nativescript-camera": "^3.2.1",
    "nativescript-cardview": "^2.0.5",
    "nativescript-checkbox": "^3.0.3",
    "nativescript-exit": "^1.0.1",
    "nativescript-feedback": "1.1.1",
    "nativescript-floatingactionbutton": "^4.1.3",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-image-swipe": "^2.1.0",
    "nativescript-imagecropper": "^0.1.2",
    "nativescript-imagepicker": "^4.0.1",
    "nativescript-intl": "^3.0.0",
    "nativescript-iqkeyboardmanager": "^1.3.0",
    "nativescript-pdf-view": "^2.0.1",
    "nativescript-permissions": "^1.2.3",
    "nativescript-pro-ui": "next",
    "nativescript-textinputlayout": "^2.0.3",
    "nativescript-theme-core": "^1.0.4",
    "nativescript-toast": "^1.4.6",
    "ngx-order-pipe": "^2.0.1",
    "reflect-metadata": "^0.1.12",
    "rxjs": "^5.5.8",
    "tns-core-modules": "^4.0.0-2018-03-27-02",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "^5.2.9",
    "@ngtools/webpack": "^1.10.2",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.10.0",
    "clean-webpack-plugin": "~0.1.19",
    "codelyzer": "3.2.2",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "^0.28.11",
    "extract-text-webpack-plugin": "~3.0.2",
    "fs-extra": "^0.30.0",
    "glob": "^7.1.2",
    "lazy": "1.0.11",
    "markdown-snippet-injector": "^0.2.0",
    "nativescript-css-loader": "~0.26.0",
    "nativescript-dev-sass": "^1.4.0",
    "nativescript-dev-typescript": "next",
    "nativescript-dev-webpack": "^0.10.0-2018-03-29-01",
    "nativescript-worker-loader": "~0.8.1",
    "node-sass": "4.5.3",
    "opener": "^1.4.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "rimraf": "^2.5.3",
    "sass-loader": "^6.0.7",
    "tar.gz": "^1.0.5",
    "tns-platform-declarations": "^3.4.1",
    "tslint": "5.8.0",
    "typescript": "~2.6.2",
    "uglifyjs-webpack-plugin": "^1.2.4",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.11.1",
    "webpack-sources": "~1.1.0"
  },
  "author": "Darts Solutions"
}

**Comment by EddyVerbruggen** [comment]
You're running the 4.0 beta, right? Am I right in concluding that the plugin works in NativeScript 3.x and doesn't work in 4.x?

**Comment by mhmo91** [comment]
Yes, correct, and when i remove the plugin, the build succeeds @EddyVerbruggen

**Comment by mhmo91** [comment]
I posted it also there
https://github.com/NativeScript/NativeScript/issues/5602

**Comment by EddyVerbruggen** [comment]
Thanks @mhmo91, I'll wait a little to see if this can be fixed in the NativeScript Android 4.x runtime.

**Comment by EddyVerbruggen** [comment]
I've added the suggestion provided in that issue and it works as expected. Please upgrade to 1.1.2 and it'll work with NativeScript 4.

**Comment by Tompote** [comment]
Hi ! I tried NS4.0 with version 1.1.2 of nativescript-feedback plugin.
Compilation worked but I'm getting this error when I try to display a feedback:
ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'Alerter' of undefined.

**Comment by EddyVerbruggen** [comment]
@Tompote did you try removing the platforms/android folder and rerun the build?

**Comment by Tompote** [comment]
Thank you for your fast answer ! It worked !
Can't believe I didn't try that ;).
