### ISSUE TITLE
Enums aren't converted into JS files for JS users

### ISSUE THREAD

**Issue by NathanaelA** [EddyVerbruggen/nativescript-feedback#2]
You have a couple different enums like the .TOP/.BOTTOM, and the type of dialog.  

If you check the JS files that are generated -- these enums don't exist in the source so when you try and  use them like your examples show it crashes...

**Comment by EddyVerbruggen** [comment]
Good way to force users to use TS. Just kidding. Do you have a suggestion how to fix that? Thx!

**Comment by NathanaelA** [comment]
Sorry, I thought marking it as exported would have worked; I'm not sure why it isn't creating JS versions of them...

**Comment by EddyVerbruggen** [comment]
Found a way. Added an [example](https://github.com/EddyVerbruggen/nativescript-feedback/tree/f893883d63f064d5f2fec8a4df0f8167d0cfeab1#javascript-1) to the readme that works with version 1.0.3.
