### ISSUE TITLE
Cannot read property 'Alerter' of undefined

### ISSUE THREAD

**Issue by LordShiroe** [EddyVerbruggen/nativescript-feedback#20]
I was trying to use this plugin and when I try to show the alert, the following error is thrown! 

`ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'Alerter' of undefined
JS: TypeError: Cannot read property 'Alerter' of undefined
JS:     at file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/nativescript-feedback/feedback.js:20:46
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
JS:     at Feedback.show (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/nativescript-feedback/feedback.js:18:16)
JS:     at MessageService.showError (file:///data/data/org.nativescript.ergymobile/files/app/shared/services/message.service.js:50:23)
JS:     at SafeSubscriber._error (file:///data/data/org.nativescript.ergymobile/files/app/login/login.component.js:34:38)
JS:     at SafeSubscriber.__tryOrUnsub (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:242:16)
JS:     at SafeSubscriber.error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:201:26)
JS:     at Subscriber._error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:132:26)
JS:     at Subscriber.error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:106:18)
JS:     at MapSubscriber.Subscriber._error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:132:26)
JS:     at MapSubscriber.Subscriber.error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:106:18)
JS:     at FilterSubscriber.Subscriber._error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:132:26)
JS:     at FilterSubscriber.Subscriber.error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/Subscriber.js:106:18)
JS:     at MergeMapSubscriber.OuterSubscriber.notifyError (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/OuterSubscriber.js:22:26)
JS:     at InnerSubscriber._error (file:///data/data/org.nativescript.ergymobile/files/app/tns_modules/rxjs/InnerSubscriber.js:26:21)`

The error must be in the line
` var alerter = com.tapadoo.alerter.Alerter.create(application.android.foregroundActivity)` of the feedback.android.js

It seems like it can't find the Alerter native library! Can anyone help me?

**Comment by EddyVerbruggen** [comment]
Are you using the CLI? Just remove the platforms folder and build again.

**Comment by LordShiroe** [comment]
Yes, thank you! That helped!
