### ISSUE TITLE
Trigger without tap

### ISSUE THREAD

**Issue by jgerryl** [EddyVerbruggen/nativescript-feedback#21]
Hi Eddy,

Thanks before for the plugin. I test it using Nativescript with Angular and it works fine. But i have a difficulty when using this feedback without a tap activity. It shows error below

> JS: ERROR Error: Uncaught (in promise): Error: java.lang.IllegalArgumentException: Activity cannot be null!
JS:     com.tapadoo.alerter.Alerter.create(Alerter.java:47)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:44)
JS:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
JS:     android.app.Activity.performStart(Activity.java:6253)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
JS:     android.app.ActivityThread.-wrap11(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5417)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
JS: Error: java.lang.IllegalArgumentException: Activity cannot be null!
JS:     com.tapadoo.alerter.Alerter.create(Alerter.java:47)
JS:     com.tns.Runtime.callJSMethodNative(Native Method)
JS:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
JS:     com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:957)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:941)
JS:     com.tns.Runtime.callJSMethod(Runtime.java:933)
JS:     com.tns.NativeScriptActivity.onStart(NativeScriptActivity.java:44)
JS:     android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
JS:     android.app.Activity.performStart(Activity.java:6253)
JS:     android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
JS:     android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
JS:     android.app.ActivityThread.-wrap11(ActivityThread.java)
JS:     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
JS:     android.os.Handler.dispatchMessage(Handler.java:102)
JS:     android.os.Looper.loop(Looper.java:148)
JS:     android.app.ActivityThread.main(ActivityThread.java:5417)
JS:     java.lang.reflect.Method.invoke(Native Method)
JS:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
JS:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

Is using tap by design? or any idea to tap programmatically? Below is my app.component.ts

import { Component } from "@angular/core";
import * as pages from "tns-core-modules/ui/page";
import { Color } from "tns-core-modules/color";
import { Feedback, FeedbackType, FeedbackPosition } from "nativescript-feedback";

@Component({
    selector: "ns-app",
    template: '<ActionBar title="{N} Feedback"><Button text="klik" (tap)="showNoIcon()"></Button>',
})

export class AppComponent {
    private feedback: Feedback;

    constructor() {
        this.feedback = new Feedback();
        this.showNoIcon();
    }
  
    public showNoIcon(): void {
      this.feedback.show({
        title: "Title only, not even an icon..",
        duration: 2000,
        // type: FeedbackType.Custom,
        onTap: () => { console.log("showNoIcon tapped"); }
      });
    }
  
    public hide(): void {
      this.feedback.hide();
    }
  }

Without "this.showNoIcon();" this plugin work fine.

**Comment by EddyVerbruggen** [comment]
Hi,

That's really strange.. the demo app has `onTap` handlers as well and they work fine. Does it help if you remove `this.showNoIcon();` from the constructor?

**Comment by jgerryl** [comment]
yes it helped me. errors gone and i can use tap on the emulator perfectly. i use `this.showNoIcon()` to trigger the feedback programmatically. Do you it's possible to trigger this feedback programmatically? Because i want to combine this with local-notifications plugin. Whenever the local notification scheduled i want to use this feedback as a "heads-up notification"

**Comment by EddyVerbruggen** [comment]
You should be able to do that, it's just that the constructor may not be the best place.
