### ISSUE TITLE
Feedback runs but doesn't appear on screen

### ISSUE THREAD

**Issue by BearOutThere** [EddyVerbruggen/nativescript-feedback#22]
Hello,  
I'm stumped by a strange issue where i can see feedback code running and i can step through it in debugger but nothing shows up on the screen.  To make the issue even stranger when the same code is run on a Mac in an android emulator feedback messages show up fine.  But when compiling on Ubuntu feedback messages don't display anywhere (Android emulator, Genymotion emulator, nor debugging on connected device. I've tried everything i could think of but can't get the feedback to show.  Any ideas or pointers would be greatly appreciated.

**page.xml:**

`
\<Page
    navigatingTo="onNavigatingTo"  
    xmlns="http://schemas.nativescript.org/tns.xsd" >

   \<GridLayout rows="*, auto" columns="*">
        \<Label text="Just label" textWrap="true" row="0" col="0" verticalAlign="center" />
        \<Button text="Feedback test" tap="{{ showMessage }}" row="1" col="0" />

   \</GridLayout>
\</Page>
`

**Code behind:**

`
import { EventData } from "data/observable";
import { NavigatedData, Page } from "ui/page";
import { TempViewModel } from "./temp-view-model";
export function onNavigatingTo(args: NavigatedData) {
    if (args.isBackNavigation) {
        return;
    }
    const page = <Page>args.object;
    page.bindingContext = new TempViewModel();
}

`

**View model:**

`
import { Observable } from "data/observable";
import { Feedback, FeedbackPosition, FeedbackType } from "nativescript-feedback";

export class TempViewModel extends Observable {
    private feedback: Feedback;
    constructor() {
        super();
        this.feedback = new Feedback();
    }
    public showMessage(): void {
        this.feedback.show({
            message: "Message body"
        });
    }
}
`

**app.gradle:**

`

android {  
  defaultConfig {  
    generatedDensities = []
    applicationId = "com.app90dayreporter"
    minSdkVersion 17
    multiDexEnabled true
  }

  project.ext {
    buildToolsVersion = "27.0.1"
    googlePlayServicesVersion = "12.0.1"  // should match Firebase plugin gradle
    supportVersion = "27.0.1"
    compileSdk = 27
    targetSdk = 27
    firebaseMessagingVersion = "+"
  }

  aaptOptions {  
    additionalParameters "--no-version-vectors"  
  } 
 
}

`

**package.json:**

`
{
  "name": "com.xxxxx",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "version": "0.1.0",

  "nativescript": {
    "id": "com.xxxxx",

    "tns-android": {
      "version": "4.0.1"
    },

    "tns-ios": {
      "version": "4.0.1"
    }

  },

  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },

  "dependencies": {
    "nativescript-feedback": "^1.1.2",
    "nativescript-plugin-firebase": "^5.3.1",
    "nativescript-purchase": "^2.0.0",
    "nativescript-theme-core": "1.0.4",
    "nativescript-toolbox": "^3.0.1",
    "nativescript-ui-dataform": "^3.5.2",
    "nativescript-ui-listview": "^3.5.4",
    "nativescript-ui-sidedrawer": "^3.5.2",
    "node-sass": "^4.9.0",
    "tns-core-modules": "^4.0.0"
  },

  "devDependencies": {
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "1.3.5",
    "nativescript-dev-typescript": "^0.5.1",
    "tslint": "5.8.0",
    "typescript": "^2.8.3"
  }

}
`

**Comment by EddyVerbruggen** [comment]
Do you think this is an issue only on Ubuntu? I don't use it so can't help you. Others perhaps?

**Comment by BearOutThere** [comment]
I'm not sure why the underlying OS would make a difference since the runtime is Android.  I think more likely some kind of environment setting or version mismatch.  I can step through the code line by line.  Can you recommend where to focus on to see if proper visual components are being called. Perhaps something is not right with the Alerter library?

**Comment by EddyVerbruggen** [comment]
I haven't got the first clue, sorry.

**Comment by BearOutThere** [comment]
So out of desperation i created a new app using the ts drawer template and added the feedback plugin to it.  It worked as it should.  So the problem must be with the application configuration.  Thanks for your great plugins.

**Comment by EddyVerbruggen** [comment]
Thanks for reporting back! Closing for now, cheers.

**Comment by BearOutThere** [comment]
So the problem had to do with the app dependencies.  Originally the app was based on the NS drawer template with TypeScript (v 3.4.0).   The latest template version is 4.0.0.  I've updated the application with the dependencies from the 4.0.0 template and reinstalled the modules.  After that feedback started working as it should.  I'm not sure exactly which dependency was missing or outdated.  But upgrading them solved the problem.

**Comment by Xsmael** [comment]
I have the same problem!, my  app is abit advanced so i cannot just chnge the base template :(

**Comment by BearOutThere** [comment]
Hey Xsmael. Please check against the NS drawer app template to confirm that you have the new versions of all libraries.  That was the problem for me.  After upgrading older versions feedback worked fine.
