### ISSUE TITLE
I get this error anytime i do a build but the alert system works perfectly after the build - using nativescript-vue

### ISSUE THREAD

**Issue by pedmindset** [EddyVerbruggen/nativescript-feedback#25]
ERROR in app.android.js from UglifyJs
Unexpected token: name (Feedback) [app.android.js:6864,6]

But there no error in app after the build
using nativescript-vue

**Comment by EddyVerbruggen** [comment]
Please post a repo showing this error, along with steps to reproduce. I can't make sense of it like this.
