### ISSUE TITLE
TypeError: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by kumarandena** [EddyVerbruggen/nativescript-feedback#28]
Hi Eddy!

I got mentioned typo error, I have tested in android device.

`JS: TypeError: Cannot read property 'create' of undefined
JS:     at Promise (file:///data/data/org.nativescript.ISM/files/app/tns_modules/nativescript-feedback/feedback.js:17:55)
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.ISM/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)
JS:     at Feedback.show (file:///data/data/org.nativescript.ISM/files/app/tns_modules/nativescript-feedback/feedback.js:15:16)
JS:     at Feedback.success (file:///data/data/org.nativescript.ISM/files/app/tns_modules/nativescript-feedback/feedback.common.js:19:21)
JS:     at HomeComponent.sendLocation (file:///data/data/org.nativescript.ISM/files/app/home/home.component.js:62:23)
JS:     at Object.eval [as handleEvent] (ng:///AppModule/HomeComponent.ngfactory.js:20:31)
JS:     at handleEvent (file:///data/data/org.nativescript.ISM/files/app/tns_modul...`

Here is my package.json
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.ISM",
    "tns-android": {
      "version": "4.1.3"
    },
    "tns-ios": {
      "version": "4.1.1"
    }
  },
  "scripts": {
    "lint": "tslint \"app/**/*.ts\""
  },
  "dependencies": {
    "@angular/animations": "~6.0.6",
    "@angular/common": "~6.0.6",
    "@angular/compiler": "~6.0.6",
    "@angular/core": "~6.0.6",
    "@angular/forms": "~6.0.6",
    "@angular/http": "~6.0.6",
    "@angular/platform-browser": "~6.0.6",
    "@angular/platform-browser-dynamic": "~6.0.6",
    "@angular/router": "~6.0.6",
    "nativescript-angular": "~6.0.6",
    "nativescript-feedback": "^1.2.0",
    "nativescript-geolocation": "^4.2.6",
    "nativescript-permissions": "^1.2.3",
    "nativescript-theme-core": "~1.0.4",
    "reflect-metadata": "~0.1.10",
    "rxjs": "~6.1.0",
    "tns-core-modules": "4.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0-beta.3",
    "@ngtools/webpack": "6.1.0-rc.0",
    "babel-traverse": "6.26.0",
    "babel-types": "6.26.0",
    "babylon": "6.18.0",
    "codelyzer": "~4.3.0",
    "lazy": "1.0.11",
    "nativescript-dev-sass": "~1.6.0",
    "nativescript-dev-typescript": "~0.7.0",
    "nativescript-dev-webpack": "~0.14.0",
    "tslint": "~5.10.0",
    "typescript": "~2.7.2"
  }
}

.thanks

**Comment by EddyVerbruggen** [comment]
Typo? Ah, Type. Lol. 

I guess you removed the Android platforms folder after adding the plugin?

**Comment by kumarandena** [comment]
:) haha. Its Type.

No, I did not  remove the platform after adding plugin. Its not working on android only. But its working fine in ios on first try itself. 

After removing and adding the android platform did the trick. Now its working fine on android also.

.thanks

**Comment by Hammad6264** [comment]
Hy @kumarandena , Did you solved the probelm???
