### ISSUE TITLE
onTap not executed if the application is in background

### ISSUE THREAD

**Issue by hackerunet** [EddyVerbruggen/nativescript-feedback#30]
Hello, I have an issue trying to navigate to a view in my application after making tap over the push notification, I'm using the feedback plugin to perform this, if the application is running it works without issues but if the application is in the background, I get the push notification but after taping over it I just get my application launched again and nothing happens in my function to navigate to the view I want. This is a reference for the same issue but in a different plugin which is similar.
https://stackoverflow.com/questions/39001751/nativescript-call-to-certain-action-after-tapping-android-push-plugin-notificati
```
this.feedback.show({
                            title: message.title,
                            message: message.body,
                            icon: "AppIcon",
                            duration: 5000,
                            backgroundColor: new Color("green"),
                            onTap:()=>{
                                this.routerExtensions.navigate(['/message/chat', id], {clearHistory:true});
                            }
                        }).then(()=>{
                        });
```
If the application is active everything works as expected, it doesn't if the application is running in the background.

**Comment by hackerunet** [comment]
Also after several tests the feedback.onTap event is not executed everytime the notification is received, it only happens once, the first time, if I receive another notification and tap over it the onTap function is not executed again, this is happening on iOS.

**Comment by Pandishpan** [comment]
@hackerunet wrap your navigation call with ngZone.run

`private ngZone: NgZone`

```
this.ngZone.run(() => this._routerExtensions.navigate(['/message/chat', id], {
                                animated: false
                                // clearHistory: true
                            })).then((done) => {
                                // console.log("navigate done");
                                // console.log(done);
                            }).catch((error) => {
                                console.log("navigate error");
                                console.log(error);
                            });
```

**Comment by hackerunet** [comment]
Too late, i moved to Flutter already.
