### ISSUE TITLE
Feedback not showing up

### ISSUE THREAD

**Issue by d3mac123** [EddyVerbruggen/nativescript-feedback#31]
Hi, 

I am running NS 4.2.2 with updated core-modules (4.2.1) and ios (4.2.0). However, for some reason I don't get, all my feedback calls stopped to work (no errors, nothing, they simply don't show anymore).

Any ideas why?

**Comment by EddyVerbruggen** [comment]
No. I run those same versions without issue. Perhaps share a repo, or better still: start a new project, add the plugin, and see what happens.

**Comment by d3mac123** [comment]
I deleted the build folder and re-run. Everything is fine now. If it is not much of work for you, can you tell me how I upload my app files to a repository I have created? I couldn't find a way to do that yet. Thanks!

**Comment by EddyVerbruggen** [comment]
When you create a new repo in the GitHub or BitBucket UI you will get very clear instructions on how to do that.
