### ISSUE TITLE
Vuejs not showing

### ISSUE THREAD

**Issue by jaasaria** [EddyVerbruggen/nativescript-feedback#33]
Is this working in vue? I tried to register it and dont know if im missing something. Hope someone can give me a hand. Pls kindly check the code bellow. thanks

`
//main.js
import { Feedback } from "nativescript-feedback";
Vue.prototype.$feedback = new Feedback() 

//vue component
this.$feedback.success({
  title: "Awesome",
  message: "That was great!"
});
`

**Comment by EddyVerbruggen** [comment]
You're running this in a standalone app? iOS/Android/both?

**Comment by jaasaria** [comment]
Hi eddy. Sorry to bother you, now its working perfectly. Thanks
