### ISSUE TITLE
Question: Preventing the feedback prompt from closing without user interaction

### ISSUE THREAD

**Issue by gabbibrooks** [EddyVerbruggen/nativescript-feedback#36]
I'm looking to show an error and have a user tap the feedback prompt in order to close it. is there an option to prevent the default duration value from being used or a number value that the duration will accept to prevent it from hiding itself?

**Comment by EddyVerbruggen** [comment]
Can’t you just show it for a very long time?

**Comment by gabbibrooks** [comment]
I can do that. I was just wondering if there was a way to do it since it seemed like the duration value was nullable but clearly has a default value. That’s fine I’ll just set it to a long value thanks
