### ISSUE TITLE
It does not work with nativescript 5.0 on the android platform. 

### ISSUE THREAD

**Issue by marcelbonfim182** [EddyVerbruggen/nativescript-feedback#41]
It does not work with nativescript 5.0 on the android platform. Nothing happens! Also, nothing appears on the console. On Nativescript 5.0, does work only on IOS platform.

**Comment by marcelbonfim182** [comment]
I programmed in pure javascript. Only work with IOS. Same code.

**Comment by EddyVerbruggen** [comment]
Share a repo with instructions on how to reproduce. Then reopen and I might take a look.

**Comment by marcelbonfim182** [comment]
Hello, here the Url repo. You just need  generate a android build and install it on your device or simulator, after load the app, in home screen, push the button: "Call Feedback". Note that nothing will happen, even on console, nothing appear.
https://github.com/marcelbonfim182/sidedrawertest

Thanks for support!

**Comment by EddyVerbruggen** [comment]
Follow-up in #42.
