### ISSUE TITLE
It does not work with nativescript 5.0 on the android platform.

### ISSUE THREAD

**Issue by marcelbonfim182** [EddyVerbruggen/nativescript-feedback#42]
It does not work with nativescript 5.0 on the android platform. Nothing happens! Also, nothing appears on the console. On Nativescript 5.0, does work only on IOS platform.

Here the Url repo. You just need generate a android build and install it on your device or simulator, after load the app, in home screen, push the button: "Call Feedback". Note that nothing will happen, even on console, nothing appear.
https://github.com/marcelbonfim182/sidedrawertest

Thanks for support!

**Comment by EddyVerbruggen** [comment]
Thanks for sharing that repo, very helpful!

Looks like the convenience methods (`success`, `warning`, etc) are broken on Android. This works though:

```js
  feedback2.show({
    title: "Awesome",
    message: "That was great!",
    duration: 2000
  });
```

I'll investigate this further today.

**Comment by EddyVerbruggen** [comment]
Aha, it has to do with the icons not being found when a `type` is set (which is implicit for the `success` (etc) functions. And that's because the resource folder may be in a different location than what the plugin expects it to be.

**Comment by EddyVerbruggen** [comment]
Please update to 1.3.3 and remove the platforms folder, then run `tns run android` and it should work again.

**Comment by bradmartin** [comment]
@EddyVerbruggen was this throwing ```Error: Uncaught (in promise): Error: android.content.res.Resources$NotFoundException: Resource ID #0x0
    android.content.res.ResourcesImpl.getValue(ResourcesImpl.java:216)``` 

I'm seeing this on a Samsung device in the wild on a production app, sentry log [here](https://sentry.io/share/issue/106c56641cf74c5fa28ea6864820e568/). 

I'm currently looking at when the 1.0.00 release was done which looks to be December 11th 2018. And we had `^1.3.1` for the dep.

**Comment by bradmartin** [comment]
Looks like `npm view` reports `1.3.3` published on Dec. 10, 2018. So I would have pulled in `1.3.3` on the 11th when the build was processed.

The sentry log stack trace reports back to a call to `warning` on feedback instance so I'll see what I can find out.

**Comment by EddyVerbruggen** [comment]
Unless package-lock.json or some other local cache said otherwise. Reason number 45347 why I hate using `^` (and even `~` in dependencies of production apps).

Can you perhaps decompile the app to make sure?

**Comment by bradmartin** [comment]
I've went thru a few builds and all the `1.3.x` versions to try and find anything.

I also avoid not pinning the version, this and one of my plugins were the only ones with `^` 🤦‍♂️ 

At any rate, this seems to be specific to this Samsung device. It works fine on my emulators and Pixel2. So I'm now looking to see if I can find anything about this device.

**Comment by bradmartin** [comment]
No worries though, for now I'm just going to use my own icon for this `.warning` usage and move on. Since only the Samsung device throws it, there is no telling what's happening 😄 

Thanks tho 👍
