### ISSUE TITLE
Icon from url

### ISSUE THREAD

**Issue by ghost** [EddyVerbruggen/nativescript-feedback#43]
Hello, I am having an issue where the icon that I am wish to use in the feedback bar I can only access via a url rather than from the App_Resources/ folder.  Would there be anyway to pass the icon property a url instead of a file name?

**Comment by EddyVerbruggen** [comment]
That doesn't sound wise as it would delay displaying feedback, or make it stutter, or it may even be downloaded after the feedback message has disappeared. AFAIK it's not possible with the underlying native library.
