### ISSUE TITLE
[!] Invalid `Podfile` file: The target `Pods` already has a platform set..

### ISSUE THREAD

**Issue by vforv** [EddyVerbruggen/nativescript-feedback#49]
I start getting this error . Is something changed in plugin?
```
 #  from platforms/ios/Podfile:85
 #  -------------------------------------------
 #  # Begin Podfile - node_modules/nativescript-feedback/platforms/ios/Podfile
 >  platform :ios, '9.0'
 #  
```

Edit I tried to delete content from node_modules/nativescript-feedback/platforms/ios/Podfile it passes build but after that I get error:

> ERROR Error: Uncaught (in promise): ReferenceError: Can't find variable: ISMessages
> file:///app/vendor.js:83034:37
> ZoneAwarePromise@file:///app/vendor.js:80266:37

**Comment by EddyVerbruggen** [comment]
Thx for reporting - bump to 1.3.9 and let me know if that helps.

**Comment by bubbleheadinc** [comment]
FYI I was getting build failures due to `ld: framework not found Protobuf` after upgrading to {N} 5.3.2 from {N} 5.1.1 and then updating pods. Upgrading nativescript-feedback to 1.3.9 fixed it.
