### ISSUE TITLE
exemples on readme inaccurate.

### ISSUE THREAD

**Issue by ajkula** [EddyVerbruggen/nativescript-feedback#5]
These are the solutions i got to get the attributes set correctly!
Amazing plugin BTW, i'll keep using it since it's way better then Toasts!
And FYI, to get the icons flag set right, go to : ".\platforms\android\src\F0\res\drawable\IconsNamesHere"

feedback.show({
                icon: "successicon",     //    'success' or 'Success' aren't working, just use that one...
                onTap: () => {
                    feedback.hide();   //  don't use 'this.feedback.hide()'
                }
});

Thank you so much for doing this Eddy!

**Comment by EddyVerbruggen** [comment]
Thanks. I am not sure which example you refer to though.

Are you using TypeScript?

**Comment by ajkula** [comment]
Hi Eddy, I'm using native JavaScript..
By exemples i meant the few ones from the readme.
This feedback plugin is AWESOME Eddy !!
Thank you soooo much!!

**Comment by ajkula** [comment]
PS would be Amazing to have a 'picture' attribute which could receive any
'~/pic.png/' uri...
