### ISSUE TITLE
ARC forbids synthesizing a property of an Objective-C object with  unspecified ownership or storage attribute

### ISSUE THREAD

**Issue by mayureshjadhav** [EddyVerbruggen/nativescript-feedback#6]
On building the application in ios I got "ARC forbids synthesizing a property of an Objective-C object with  unspecified ownership or storage attribute issue. I am using nativescript 2.5 for building the application.

**Comment by EddyVerbruggen** [comment]
When do you see this? With which Xcode version? For which device/sim? Does it haper functionality?

**Comment by mayureshjadhav** [comment]
I am using Xcode 7.1 and device is iphone 6S plus

**Comment by mayureshjadhav** [comment]
At the time of executing the tns run ios command

**Comment by EddyVerbruggen** [comment]
But is it an error or just a warning (Does it haper functionality)? An in case of an error, does upgrading to Xcode 8 help?

**Comment by mayureshjadhav** [comment]
By upgrading to Xcode 8 it works. Thanks. 👍
