### ISSUE TITLE
IOS  Not Working

### ISSUE THREAD

**Issue by rinnegan007** [EddyVerbruggen/nativescript-feedback#60]
Hi, first thanks for the plugin.

I am not getting the plugin to work on IOS using the TNS PREVIEW command.

Error:  "ReferenceError: Can't find variable: SCLAlertView"

The same problem is also found in the other plugins of his own.

nativescript-feedback
@nstudio/nativescript-snackbar
nativescript-fancyalert

Thanks!

**Comment by EddyVerbruggen** [comment]
Hi, yep - and the same for any other plugin which has native dependencies (like `SCLAlertView`) which aren't bundled with the Preview app. If you want to test those kinds of plugins, please deploy your app as a standalone instead of part of the Preview "wrapper" app.
