### ISSUE TITLE
[Android] TypeError this.lastAlert.getTitle is not a function

### ISSUE THREAD

**Issue by mhtghn** [EddyVerbruggen/nativescript-feedback#66]
Hi,

Ive updated to 1.4.0 from 1.3.11 which was working fine apart from an issue with Android Notch

With this version the handling of Android notch is perfect and the feedbacks are working fine, but I always have a error message in the logs everytime I try to show a feedback 

```
JS: ERROR Error: Uncaught (in promise): TypeError: this.lastAlert.getTitle is not a function
JS: TypeError: this.lastAlert.getTitle is not a function
JS:     at file:///node_modules/nativescript-feedback/feedback.js:95:0
JS:     at new ZoneAwarePromise (file:///node_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:0)
JS:     at Feedback.show (file:///node_modules/nativescript-feedback/feedback.js:15:0)
JS:     at Feedback.error (file:///node_modules/nativescript-feedback/feedback.common.js:27:0)
```

**Comment by kaliosek** [comment]
Hi, the same error is with getText(). Tested on android simulator.
````

JS: ERROR Error: Uncaught (in promise): TypeError: this.lastAlert.getText is not a function
JS: TypeError: this.lastAlert.getText is not a function
JS:     at file: node_modules/nativescript-feedback/feedback.android.js:96:0
JS:     at new ZoneAwarePromise (file: node_modules/@nativescript/angular/zone-js/dist/zone-nativescript.js:902:0)
JS:     at Feedback.show (file: node_modules/nativescript-feedback/feedback.android.js:15:0)
JS:     at Feedback.success (file: node_modules/nativescript-feedback/feedback.common.js:19:0)
JS:     at SafeSubscriber._next (file: src/app/modules/auth/components/password-reset/confirmation/confirmation.component.ts:89:26)

**Comment by bellalMohamed** [comment]
regarding this issue I did some debugging and researches here's what I found.
setTitleAppearance
```getTitle()``` && ```getText()``` functions have been removed from the main plugin, but fortunately someone opened an issue to bring back these two functions, and hopefully he'll submit a PR soon [Set color / fontsize dynamically #228](https://github.com/Tapadoo/Alerter/issues/228)

as a temporary fix right now we can use "setTitleAppearance" and "setTextAppearance" to change title and text color, but unfortunately there's no possible way to change the font size - as far as I know and tried -

I've fixed this issue but didn't make a PR as it will contain breaking changes for people expecting to be able to resize, but lookin to the current state that we're getting errors either ways I'll make a PR.

@EddyVerbruggen will appreciate your answer

**Comment by EddyVerbruggen** [comment]
Sounds like folks will need to use the previous plugin version if they need those features. Would be great if the upstream merges a PR to bring 'em back!

**Comment by dosomder** [comment]
I will make PR to the plugin and then make a PR here as well to fix it!
