### ISSUE TITLE
Call feedback in a barcode scanner promise

### ISSUE THREAD

**Issue by leocrawf** [EddyVerbruggen/nativescript-feedback#8]
I am trying to call the feedback in a barcode scanner feedback but it does not work. Here is my code.
    var barcodescanner = new BarcodeScanner();
   barcodescanner.scan({
    formats: "QR_CODE",   // Pass in of you want to restrict scanning to certain types
    .... //more options
  }).then(
      function(result) {
          var r = result.text.split("|");
        //1. verification checks such as gps lat, lang range etc.
         if(result is not in range){
             var feedback = new FeedbackPlugin.Feedback();
            feedback.error({
              title: "Error: Please enable an internet connection!"
             });
         } else {
             //do something else
          }
       },
      function(error) {
        console.log("No scan: " + error);
      }
  );

**Comment by EddyVerbruggen** [comment]
Is the scanner hidden before you try showing feedback? Try using a timeout before showing feedback perhaps?

**Comment by leocrawf** [comment]
Hi,

By the time that code is evaluated scanner would have been hidden. Thanks for your response I will give it a try.

**Comment by leocrawf** [comment]
Thank you . You saved me a whole lot of redirects to error screens.

**Comment by EddyVerbruggen** [comment]
Nice!
