### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by mendokar** [EddyVerbruggen/nativescript-feedback#9]
Good afternoon Eddy Verbruggen, you know if there is any way to change the font of alerts, thanks

**Comment by EddyVerbruggen** [comment]
Hi, can you please investigate if that's supported by the libraries we depend on? They're mentioned [here](https://github.com/EddyVerbruggen/nativescript-feedback#credits).

**Comment by mendokar** [comment]
Custom Fonts and Text Appearance

 Alerter.create(ExampleActivity.this)
                .setTitle("Alert Title")
                .setTitleAppearance(R.style.AlertTextAppearance_Title)
                .setTitleTypeface(Typeface.createFromAsset(getAssets(), "Pacifico-Regular.ttf"))
                .setText("Alert text...")
                .setTextAppearance(R.style.AlertTextAppearance_Text)
                .setTextTypeface(Typeface.createFromAsset(getAssets(), "ScopeOne-Regular.ttf"))
                .show();

**Comment by abhayastudios** [comment]
@eddy any idea when 1.2.0 will be released? I am eagerly awaiting this feature :)

Thanks!

**Comment by EddyVerbruggen** [comment]
Hey @abhayastudios! It's been published to npm 24 days ago (see https://www.npmjs.com/package/nativescript-feedback), I just forgot to do the bookkeeping in Github.

See the updated README for usage.
